2020-10-21 20:15:11,719 INFO    MainThread:20717 [internal.py:wandb_internal():62] W&B internal server running at pid: 20717
2020-10-21 20:15:11,722 DEBUG   HandlerThread:20717 [handler.py:handle_request():54] handle_request: check_version
2020-10-21 20:15:11,722 INFO    WriterThread:20717 [datastore.py:open_for_write():76] open: wandb/run-20201021_201510-2opa4kwr/run-2opa4kwr.wandb
2020-10-21 20:15:11,725 DEBUG   SenderThread:20717 [sender.py:send():88] send: header
2020-10-21 20:15:11,750 DEBUG   SenderThread:20717 [sender.py:send():88] send: request
2020-10-21 20:15:11,763 DEBUG   SenderThread:20717 [sender.py:send_request():97] send_request: check_version
2020-10-21 20:15:11,768 DEBUG   Thread-4  :20717 [connectionpool.py:_new_conn():943] Starting new HTTPS connection (1): pypi.org:443
2020-10-21 20:15:11,805 DEBUG   Thread-4  :20717 [connectionpool.py:_make_request():442] https://pypi.org:443 "GET /pypi/wandb/json HTTP/1.1" 200 50840
2020-10-21 20:15:11,818 DEBUG   SenderThread:20717 [sender.py:send():88] send: run
2020-10-21 20:15:11,845 DEBUG   SenderThread:20717 [cmd.py:execute():719] Popen(['git', 'cat-file', '--batch-check'], cwd=/rwthfs/rz/cluster/home/zk315372/Chinmay/Git/HN-tumour-segmentation, universal_newlines=False, shell=None, istream=<valid stream>)
2020-10-21 20:15:11,878 DEBUG   SenderThread:20717 [connectionpool.py:_new_conn():943] Starting new HTTPS connection (1): api.wandb.ai:443
2020-10-21 20:15:11,890 WARNING MainThread:20717 [internal.py:wandb_internal():116] Internal process interrupt: 1
2020-10-21 20:15:12,077 DEBUG   SenderThread:20717 [connectionpool.py:_make_request():442] https://api.wandb.ai:443 "POST /graphql HTTP/1.1" 200 None
2020-10-21 20:15:12,085 INFO    SenderThread:20717 [dir_watcher.py:__init__():167] watching files in: wandb/run-20201021_201510-2opa4kwr/files
2020-10-21 20:15:12,086 INFO    SenderThread:20717 [sender.py:_start_run_threads():469] run started: 2opa4kwr with start time 1603304110
2020-10-21 20:15:12,660 WARNING MainThread:20717 [internal.py:wandb_internal():116] Internal process interrupt: 2
2020-10-21 20:15:12,660 ERROR   MainThread:20717 [internal.py:wandb_internal():119] Internal process interrupted.
2020-10-21 20:15:12,819 INFO    WriterThread:20717 [datastore.py:close():257] close: wandb/run-20201021_201510-2opa4kwr/run-2opa4kwr.wandb
2020-10-21 20:15:12,819 INFO    HandlerThread:20717 [handler.py:finish():267] shutting down handler
2020-10-21 20:15:13,087 INFO    SenderThread:20717 [sender.py:finish():588] shutting down sender
2020-10-21 20:15:13,087 INFO    SenderThread:20717 [dir_watcher.py:finish():280] shutting down directory watcher
2020-10-21 20:15:14,086 INFO    SenderThread:20717 [dir_watcher.py:finish():309] scan: wandb/run-20201021_201510-2opa4kwr/files
2020-10-21 20:15:14,087 INFO    SenderThread:20717 [dir_watcher.py:finish():315] scan save: wandb/run-20201021_201510-2opa4kwr/files/config.yaml config.yaml
2020-10-21 20:15:14,105 INFO    SenderThread:20717 [file_pusher.py:finish():169] shutting down file pusher
2020-10-21 20:15:14,105 INFO    SenderThread:20717 [file_pusher.py:join():174] waiting for file pusher
2020-10-21 20:15:14,113 DEBUG   Thread-10 :20717 [connectionpool.py:_new_conn():943] Starting new HTTPS connection (1): api.wandb.ai:443
2020-10-21 20:15:14,289 DEBUG   Thread-10 :20717 [connectionpool.py:_make_request():442] https://api.wandb.ai:443 "POST /graphql HTTP/1.1" 200 None
2020-10-21 20:15:14,298 DEBUG   Thread-10 :20717 [connectionpool.py:_new_conn():943] Starting new HTTPS connection (1): storage.googleapis.com:443
2020-10-21 20:15:14,649 DEBUG   Thread-10 :20717 [connectionpool.py:_make_request():442] https://storage.googleapis.com:443 "PUT /wandb-production.appspot.com/cnmy-ro/hn-gtv-segmentation/2opa4kwr/config.yaml?Expires=1603390514&GoogleAccessId=gorilla-cloud-storage%40wandb-production.iam.gserviceaccount.com&Signature=Z4pTwry9hV7CXTWJLlFm3VMfPRdXNGAvlMSXUI3dAs1a%2Fb6l%2FWHUig9xKxB73ZfvjwyeZD%2BS1v4T5J4MM2Z7kVN1KuRcnhQT74GyYLNj7RUWpFU4LKnFhgxf5xGoks4eEmWi%2BLV1e2WFs0EJkaJfb4HpOX%2FYzJLfj7wqmPJS%2BgzW50VEr9WoeOR5I3km6L5j4nCIWMYSRpXiEdqJBpfc9Pjopdj%2B1Cq8Wsrw8VdnETodAFzqB7HJLls2N2jgJf6G8975umj4V%2BD%2Fi0aExtvVvZbKGksiyqlsWZ62d4%2F0%2FSZgxFICf0qT7CQ86K5JErfsUTO0VVN8sY49Q%2B6YHtaBhQ%3D%3D HTTP/1.1" 200 0
2020-10-21 20:15:14,651 INFO    Thread-10 :20717 [upload_job.py:push():112] Uploaded file wandb/run-20201021_201510-2opa4kwr/files/config.yaml
2020-10-21 20:15:15,110 DEBUG   Thread-5  :20717 [connectionpool.py:_new_conn():943] Starting new HTTPS connection (1): api.wandb.ai:443
2020-10-21 20:15:15,271 DEBUG   Thread-5  :20717 [connectionpool.py:_make_request():442] https://api.wandb.ai:443 "POST /files/cnmy-ro/hn-gtv-segmentation/2opa4kwr/file_stream HTTP/1.1" 200 None
2020-10-21 20:15:15,274 INFO    MainThread:20717 [internal.py:handle_exit():137] Internal process exited
